#!/bin/bash
set -ex

oc new-project kubevirt-web-ui
cd deploy

oc apply -f service_account.yaml
oc apply -f scc_anyuid.yaml

oc apply -f role.yaml
oc apply -f role_extra_for_console.yaml
oc apply -f role_kube-public.yaml

oc apply -f role_binding.yaml
oc apply -f role_binding_extra_for_console.yaml
oc apply -f role_binding_kube-public.yaml

oc apply -f crds/kubevirt_v1alpha1_kwebui_crd.yaml
oc apply -f operator.yaml

oc apply -f crds/kubevirt_v1alpha1_kwebui_cr.yaml

oc get kwebui
oc get pods

